version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5438:5432"
    volumes:
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./pgpass:/var/lib/postgresql/.pgpass
      - ./config-postgresql:/var/lib/postgresql/data/postgresql.conf

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      API_TOKEN: ${API_TOKEN}
      SSH_HOST: ${SSH_HOST}
      SSH_PORT: ${SSH_PORT}
      SSH_USER: ${SSH_USER}
      SSH_PASS: ${SSH_PASS}